MERGE INTO GENRE KEY (GENRE_ID) VALUES (1, 'КОМЕДИЯ');
MERGE INTO GENRE KEY (GENRE_ID) VALUES (2, 'ДРАМА');
MERGE INTO GENRE KEY (GENRE_ID) VALUES (3, 'МУЛЬТФИЛЬМ');
MERGE INTO GENRE KEY (GENRE_ID) VALUES (4, 'ТРИЛЛЕР');
MERGE INTO GENRE KEY (GENRE_ID) VALUES (5, 'ДОКУМЕНТАЛЬНЫЙ');
MERGE INTO GENRE KEY (GENRE_ID) VALUES (6, 'БОЕВИК');

MERGE INTO MPA KEY (MPA_ID) VALUES (1, 'G');
MERGE INTO MPA KEY (MPA_ID) VALUES (2, 'PG');
MERGE INTO MPA KEY (MPA_ID) VALUES (3, 'PG-13');
MERGE INTO MPA KEY (MPA_ID) VALUES (4, 'R');
MERGE INTO MPA KEY (MPA_ID) VALUES (5, 'NC-17');